# Generated by Django 2.2 on 2019-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190418_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='punkt',
            name='kg',
            field=models.IntegerField(default=45432, verbose_name='Katastralgemeinde'),
            preserve_default=False,
        ),
    ]
