# Generated by Django 2.2 on 2019-04-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_punkt_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punkt',
            name='kg',
            field=models.CharField(max_length=5, verbose_name='Katastralgemeinde'),
        ),
        migrations.AlterField(
            model_name='reservierung',
            name='kg',
            field=models.CharField(max_length=5, verbose_name='Katastralgemeinde'),
        ),
    ]
