# Generated by Django 2.2 on 2019-04-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190426_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservierung',
            name='valid_to',
            field=models.DateTimeField(),
        ),
    ]
