# Generated by Django 2.2 on 2019-04-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190426_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservierung',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
